#!/usr/bin/env python3
"""Merge the per-pad netlists back into one file, and check they agree.

split_pads.py writes each pad as a self-contained netlist, so every cell that
several pads share is written out once per pad. That redundancy is the point
worth checking: if two pads disagree about what sg13g2_Clamp_N15N15D is, the
split lost information and the per-pad LVS results do not describe the same
library.

This merges them, refuses to merge if any two pads define the same subckt
differently, and diffs the result against the monolithic netlist it came from.

  python3 recombine_pads.py [pad_dir] [out.spi] [reference.spi]

Defaults: netlist/pads_sub -> netlist/sg13g2_io_recombined.spi
          compared against netlist/sg13g2_io_sub.spi

Cells the reference has but no pad instantiates (the corner, the fillers, the
gallery) are reported, not treated as an error.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent
SRC = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "netlist" / "pads_sub"
DST = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "netlist" / "sg13g2_io_recombined.spi"
REF = pathlib.Path(sys.argv[3]) if len(sys.argv) > 3 else ROOT / "netlist" / "sg13g2_io_sub.spi"


def blocks(path):
    """{subckt name: [normalised lines]}, plus the lines outside any subckt."""
    subckts, outside = {}, []
    name, buf = None, []
    for line in path.read_text().splitlines():
        s = re.sub(r"\s+", " ", line.strip())
        if s.lower().startswith(".subckt"):
            name, buf = s.split()[1], [s]
        elif s.lower().startswith(".ends"):
            if name:
                subckts[name] = buf
            name = None
        elif not s or s.startswith("*"):
            continue
        elif name is not None:
            buf.append(s)
        else:
            outside.append(s)
    return subckts, outside


pads = sorted(SRC.glob("*.spi"))
if not pads:
    sys.exit(f"no .spi files in {SRC}")

merged, first_seen, globals_seen = {}, {}, []
disagree = []
for pad in pads:
    subckts, outside = blocks(pad)
    for g in outside:
        if g.lower().startswith(".global") and g not in globals_seen:
            globals_seen.append(g)
    for cell, body in subckts.items():
        if cell in merged and merged[cell] != body:
            disagree.append((cell, first_seen[cell], pad.name))
        merged[cell] = body
        first_seen.setdefault(cell, pad.name)

print(f"{len(pads)} pad netlists -> {len(merged)} unique subcircuits")

if disagree:
    print(f"\nERROR: {len(disagree)} subcircuits are defined differently by different pads:")
    for cell, a, b in disagree:
        print(f"  {cell}: {a} vs {b}")
    sys.exit(1)
print("no subcircuit is defined two different ways")

# Whether this came from the LVS form or the simulatable one. convert_netlist.py
# rewrites device calls as M/D/R elements for KLayout's reader; ngspice needs
# them as subcircuit calls, so the two forms are mutually exclusive and it is
# worth saying which one this is at the top of the file.
is_lvs = any(ln[:1] in "MDR" and ln.split()[-1][0] not in "0123456789"
             for body in merged.values() for ln in body[1:] if ln)

out = ["* Recombined from " + str(SRC),
       "* Generated by recombine_pads.py; do not edit.",
       "* LVS netlist: device lines use SPICE element prefixes and will not simulate."
       if is_lvs else
       "* Simulatable netlist: device calls are subcircuit calls, as ngspice wants.",
       ""]
out += globals_seen + [""]
for cell in sorted(merged):
    out += merged[cell] + [".ends", ""]
DST.write_text("\n".join(out) + "\n")
print(f"wrote {DST}")

if not REF.exists():
    sys.exit(0)

ref, _ = blocks(REF)
missing = sorted(set(ref) - set(merged))
extra = sorted(set(merged) - set(ref))
differ = sorted(c for c in set(ref) & set(merged) if ref[c] != merged[c])

print(f"\nagainst {REF.name}: {len(ref)} subcircuits")
print(f"  identical            {len(set(ref) & set(merged)) - len(differ)}")
print(f"  differing            {len(differ)}  {differ}")
print(f"  only in reference    {len(missing)}  {missing}")
print(f"  only in recombined   {len(extra)}  {extra}")
sys.exit(1 if differ or extra else 0)
